server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_db
    username: yerkebulan
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
