version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: football_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: football_db
      POSTGRES_USER: yerkebulan
      POSTGRES_PASSWORD: Password123
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: football_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # web UI

volumes:
  pgdata:
